###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Docker Build Test

on: [push]

jobs:
  build:
    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
